[package]
name = "rrd2whisper"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]
edition = "2018"
license = "GPLv2+"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
whisper = { path = "../whisper" }
rrd = { path = "../rrd" }
