freebsd_instance:
  image_family: freebsd-14-0

task:
  # This name gets reported as a build status in GitHub
  name: stable x86_64-unknown-freebsd
  env:
    RUST_BACKTRACE: 1
  install_script:
    - pkg install -y devel/pkgconf curl rrdtool
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo build --all --verbose
    - cargo test --all -- --nocapture
    - |
      # Disable optimisation for bench build
      cat <<'CARGO' >> Cargo.toml
      [profile.bench]
      opt-level = 0
      debug = true
      CARGO
      cargo build --benches --verbose
