freebsd_instance:
  image: freebsd-11-1-release-amd64

task:
  # This name gets reported as a build status in GitHub
  name: stable x86_64-unknown-freebsd
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - pkg install -y curl rrdtool
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - rustup component add rustfmt
  test_script:
    - . $HOME/.cargo/env
    - cargo fmt --all -- --check
    - cargo build --verbose
    - cargo test -- --nocapture
    - |
      # Disable optimisation for bench build
      cat <<'CARGO' >> Cargo.toml
      [profile.bench]
      opt-level = 0
      debug = true
      CARGO
      cargo build --benches --verbose
