windows_container:
  image: cirrusci/windowsservercore:2016

task:
  env:
    CIRRUS_SHELL: powershell
    RUST_BACKTRACE: 1
  matrix:
    - name: stable-x86_64-pc-windows-msvc
      env:
        target: x86_64-pc-windows-msvc
  setup_script:
    - 'Set-PSDebug -Trace 1; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile("https://win.rustup.rs/", "$pwd/rustup-init.exe"); "$pwd/rustup-init.exe" -yv --default-toolchain stable --default-host $env:target
    - $env:Path += "$env:userprofile\.cargo\bin"
    - rustc -vV
    - cargo -vV
  test_script:
    - $env:Path += "$env:userprofile\.cargo\bin"
    - cargo build --verbose
    - cargo test -- --nocapture
