language: rust
cache: cargo
sudo: required

rust:
  - stable

os:
  - osx
  - linux

services:
  - docker

addons:
  apt:
    packages:
      - libssl-dev

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update ; sudo apt install -y librrd-dev rrdtool ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install rrdtool ; fi

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - |
    # Disable optimisation for bench build
    cat <<'CARGO' >> Cargo.toml
    [profile.bench]
    opt-level = 0
    debug = true
    CARGO
  - cargo build --all --verbose
  - cargo test --all --no-fail-fast -- --nocapture
  - cargo build --all --benches --verbose

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:latest sh -c "\
        apt update \
        && apt install -y librrd-dev rrdtool \
        && cargo tarpaulin -f -t 5 --out Xml -v"
      bash <(curl -s https://codecov.io/bash)
    fi
