language: rust
cache: cargo
sudo: false
rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo build --benches --verbose
  - RUST_BACKTRACE=1 cargo test -- --nocapture
