language: rust
cache: cargo
sudo: required

rust:
  - nightly
  - beta
  - stable

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libssl-dev

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo test -- --nocapture
  - |
    # Disable optimisation for bench build
    cat <<'CARGO' >> Cargo.toml
    [profile.bench]
    opt-level = 0
    debug = true
    CARGO
    cargo build --benches --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CARGO_TARGET_DIR="$(pwd)/target"
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force --git https://github.com/xd009642/tarpaulin --tag 0.6.6 cargo-tarpaulin
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
