language: rust
cache: cargo
sudo: required

rust:
  - stable

os:
  - osx
  - linux
  - windows

addons:
  apt:
    packages:
      - libssl-dev

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo test --no-fail-fast -- --nocapture
  - |
    # Disable optimisation for bench build
    cat <<'CARGO' >> Cargo.toml
    [profile.bench]
    opt-level = 0
    debug = true
    CARGO
    cargo build --benches --verbose
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CARGO_TARGET_DIR="$(pwd)/target"
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force --git https://github.com/AnderEnder/tarpaulin --branch stable-master cargo-tarpaulin
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo tarpaulin --skip-clean -f -t 5 --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
