language: rust
cache: cargo
sudo: required

rust:
  - stable

os:
  - osx
  - linux
  - windows

services:
  - docker

addons:
  apt:
    packages:
      - libssl-dev

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo test --no-fail-fast -- --nocapture
  - |
    # Disable optimisation for bench build
    cat <<'CARGO' >> Cargo.toml
    [profile.bench]
    opt-level = 0
    debug = true
    CARGO
    cargo build --benches --verbose

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:develop-nightly sh -c "apt-get install libssl-dev && cargo tarpaulin --skip-clean -f -t 5 --out Xml"
      bash <(curl -s https://codecov.io/bash)
    fi
