language: rust
cache: cargo
sudo: false
rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test -- --nocapture
  - |
    # Disable optimisation for bench build
    cat <<'CARGO' >> Cargo.toml
    [profile.bench]
    opt-level = 0
    debug = true
    CARGO
    cargo build --benches --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
    fi

after_success:
  - |
    set -x
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo tarpaulin --out Xml --no-count
      bash <(curl -s https://codecov.io/bash)
    fi
