[package]
name = "carbon"
description = "Carbon"
version = "0.1.0"
authors = ["Andrii Radyk <ander.ender@gmail.com>"]
license = "MIT"
repository = "https://github.com/GiantPlantsSociety/graphite-rs"

[dependencies]
failure = "0.1.1"
lazy_static = "1"
regex = "1"
whisper = { path = "../whisper" }
