[package]
name = "rrd-sys"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]
edition = "2018"
license = "GPLv2+"

[dependencies]
libc = "0.2"

[build-dependencies]
system-deps = "7.0.0"

[package.metadata.system-deps]
librrd = "^1.7"
